# Change these first
owner: fsdh-pfds # Your GitHub organization or username, where this repository lives
repo: status-statut # The name of this repository
sites:
  - name: Datahub Home
    url: https://sds.canada.ca
  - name: Production FSDH Portal
    url: https://federal-science-datahub.canada.ca/login

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status-statut.sds.canada.ca 
  baseUrl: /status-statut
  name: "Status-Statut"
  introTitle: "Federal Science DataHub (FSDH) / Plateforme fédérale de données scientifiques (PFDS) "
  introMessage: Status page for FSDH products / Page de statut pour les produits du PFDS
  themeUrl: gcds-theme.css
  customHeadHtml: |
    <!-- Icons Font Awesome (to access icons, import Font Awesome) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" crossorigin="anonymous">
    <!-- GC Design System -->
    <link rel="stylesheet" href="https://cdn.design-system.alpha.canada.ca/@cdssnc/gcds-components@0.32.0/dist/gcds/gcds.css">
    <script type="module" src="https://cdn.design-system.alpha.canada.ca/@cdssnc/gcds-components@0.32.0/dist/gcds/gcds.esm.js"></script>
    <script nomodule src="https://cdn.design-system.alpha.canada.ca/@cdssnc/gcds-components@0.32.0/dist/gcds/gcds.js"></script>

  customBodyHtml: |
    <gcds-header signature-variant=colour> 
        <gcds-top-nav slot=menu label="Top navigation" alignment=right>
            <gcds-nav-link href=/status-statut/ slot=home>Status-Statut</gcds-nav-link>
            <gcds-nav-link href="https://github.com/fsdh-pfds/status-statut/" slot>GitHub</gcds-nav-link>
        </gcds-top-nav>
    </gcds-header>

i18n:
  activeIncidents: Active Incidents / Incidents actifs
  allSystemsOperational: All systems are operational / Tous les systèmes sont opérationnels
  incidentReport: "Incident #$NUMBER report / Rapport d'incident #$NUMBER →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts / Ouvert à $DATE avec des postes $POSTS
  incidentTitle: Incident $NUMBER Details / Détails de l'incident $NUMBER
  incidentDetails: Incident Details / Détails de l'incident
  incidentFixed: Fixed / Fixé
  incidentOngoing: Ongoing / En cours
  incidentOpenedAt: Opened at / Ouvert à
  incidentClosedAt: Closed at / Fermé à
  incidentViewOnGitHub: View and Subscribe on GitHub / Voir et s'abonner sur GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR / Posté à $DATE par $AUTHOR
  incidentBack: ← Back to all incidents / Retour à tous les incidents
  pastIncidents: Past Incidents / Incidents passés
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts / Résolu en $MINUTES minutes avec les messages $POSTS
  liveStatus: Live Status / Statut en direct
  overallUptime: "Overall uptime / Temps de fonctionnement global: $UPTIME"
  overallUptimeTitle: Overall uptime / Temps de fonctionnement global
  averageResponseTime: "Average response time / Temps de réponse moyen : $TIMEms"
  averageResponseTimeTitle: Average response / Réponse moyenne
  sevelDayResponseTime: 7-day response time / Délai de réponse de 7 jours
  responseTimeMs: Response time (ms) / Temps de réponse (ms)
  up: Up / Opérationnel
  down: Down / En panne
  degraded: Degraded / Détérioré
  loading: Loading / Chargement
  footer: Federal Science DataHub / Plateforme fédérale de données scientifiques 
  pastScheduledMaintenance: Past Scheduled Maintenance / Maintenance programmée passée
  scheduledMaintenance: Scheduled Maintenance / Maintenance programmée
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes / Démarré à $DATE pour $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes / Commence à $DATE pour $DURATION minutes
  startedAt: Started at / Commencé à
  startsAt: Starts at / Commence à
  duration: Duration / Durée
  durationMin: $DURATION minutes
  incidentCompleted: Completed / Complété
  incidentScheduled: Scheduled / Programmé
