---
name: Configure CI
on:
  push:
    paths:
      - ".upptimerc.yml"
  repository_dispatch:
    types: [setup]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Configure Upptime
    runs-on: ubuntu-latest
    steps:
      - name: Create App token
        id: create_token
        uses: fsdh-pfds/.github/.github/actions/create-app-token@main
        with:
          app-id: ${{ vars.FSDH_UPPTIME_BOT_APP_ID }}
          private-key: ${{ secrets.FSDH_UPPTIME_BOT_APP_KEY }}
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.create_token.outputs.token }}
      - name: Update template
        uses: upptime/uptime-monitor@6996123d80fe861b66994b257d4e0eb99d9d7db6 # v1.40.1
        with:
          command: "update-template"
        env:
          GH_PAT: ${{ steps.create_token.outputs.token }}
      - name: Remove workflows files
        run: |
          FILES_TO_REMOVE=(".github/workflows/summary.yml" ".github/workflows/uptime.yml" ".github/workflows/response-time.yml" ".github/workflows/graphs.yml" ".github/workflows/update-template.yml" ".github/workflows/site.yml" ".github/workflows/setup.yml")
          REMOVED=false
          for file in "${FILES_TO_REMOVE[@]}"; do
            if [ -f "$file" ]; then
              echo "File $file found. Removing..."
              git rm "$file"
              REMOVED=true
            else
              echo "File $file not found. Skipping removal."
            fi
          done
          if [ "$REMOVED" = true ]; then
            git config user.name "Upptime Bot"
            git config user.email "73812536+upptime-bot@users.noreply.github.com"
            git commit -m "Remove workflows files: ${FILES_TO_REMOVE[*]}"
            git push origin ${{ github.head_ref }}
          fi
      - name: Update response time
        uses: upptime/uptime-monitor@6996123d80fe861b66994b257d4e0eb99d9d7db6 # v1.40.1
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ steps.create_token.outputs.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: Update summary in README
        uses: upptime/uptime-monitor@6996123d80fe861b66994b257d4e0eb99d9d7db6 # v1.40.1
        with:
          command: "readme"
        env:
          GH_PAT: ${{ steps.create_token.outputs.token }}
      - name: Generate graphs
        uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1
        with:
          workflow: Graphs CI
          token: ${{ steps.create_token.outputs.token }}
      - name: Generate site
        uses: upptime/uptime-monitor@6996123d80fe861b66994b257d4e0eb99d9d7db6 # v1.40.1
        with:
          command: "site"
        env:
          GH_PAT: ${{ steps.create_token.outputs.token }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: ./site/status-page/__sapper__/export/



  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
